export default function Footer() {
  return (
    <footer className="w-full bg-slate-50 border-t border-slate-200 mt-20">
      <div className="max-w-6xl mx-auto px-4 py-10 grid grid-cols-1 md:grid-cols-3 gap-10">

        {/* Block 1 */}
        <div>
          <h3 className="font-bold text-slate-800 mb-2">Certif-Scope</h3>
          <p className="text-sm text-slate-600">
            Independent ESG Screening Service<br />
            Generated by Certif-Scope Automated Engine.<br />
            Operated by TimeProofs.
          </p>
        </div>

        {/* Block 2 */}
        <div>
          <h3 className="font-bold text-slate-800 mb-2">Legal</h3>
          <ul className="text-sm text-slate-600 space-y-1">
            <li><a href="/legal">Legal Notice</a></li>
            <li><a href="/privacy">Privacy Policy</a></li>
            <li><a href="/terms">Terms & Refund</a></li>
            <li><a href="/verify">Verify an Attestation</a></li>
          </ul>
        </div>

        {/* Block 3 */}
        <div>
          <h3 className="font-bold text-slate-800 mb-2">Operator</h3>
          <p className="text-sm text-slate-600">
            TimeProofs — Jeason Alexandre Bacoul<br />
            SIREN: 999356439<br />
            3 rue de l’Église de Louppy,<br />
            55000 Les Hauts-de-Chée, France<br />
            Email: contact@timeproofs.io
          </p>
        </div>
      </div>
    </footer>
  );
}
