import Head from "next/head";
import React from "react";
import Link from "next/link";

export default function RefundPolicy() {
  return (
    <>
      <Head>
        <title>Refund Policy — Certif-Scope</title>

        <meta
          name="description"
          content="Refund policy for Certif-Scope digital CO₂ attestations. Immediate delivery, non-refundable items, EU Directive 2011/83/UE compliance, and exceptional refund cases."
        />

        <link rel="canonical" href="https://certif-scope.com/refund-policy" />
        <meta name="robots" content="index, follow" />

        {/* OG */}
        <meta property="og:title" content="Refund Policy — Certif-Scope" />
        <meta
          property="og:description"
          content="Understand Certif-Scope’s refund rules for instantly delivered digital CO₂ attestations."
        />
        <meta property="og:type" content="article" />
        <meta property="og:image" content="https://certif-scope.com/og-image.png" />

        {/* Twitter */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Refund Policy — Certif-Scope" />
        <meta
          name="twitter:description"
          content="Refund conditions for instantly delivered CO₂ attestations generated by Certif-Scope."
        />
        <meta name="twitter:image" content="https://certif-scope.com/og-image.png" />

        {/* Structured Data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "RefundPolicy",
              name: "Refund Policy",
              url: "https://certif-scope.com/refund-policy",
              description:
                "Refund policy for instantly delivered digital CO₂ attestations generated by Certif-Scope in compliance with EU digital content regulations.",
              publisher: {
                "@type": "Organization",
                name: "Certif-Scope",
              },
            }),
          }}
        />
      </Head>

      <div className="min-h-screen bg-[#F8FAFC] text-[#1E293B]">
        <div className="max-w-3xl mx-auto px-6 py-20">

          {/* BACK */}
          <Link
            href="/"
            className="inline-block mb-10 text-sm font-semibold text-[#1FB6C1] hover:text-[#17A2AC]"
          >
            ← Back to Certif-Scope
          </Link>

          {/* TITLE */}
          <h1 className="text-3xl md:text-4xl font-black mb-4 text-[#0B3A63]">
            Refund Policy
          </h1>

          <p className="text-sm text-slate-600 mb-10">
            Certif-Scope is a service operated by <strong>TimeProofs</strong> and complies with EU consumer and digital content regulations.
          </p>

          <div className="space-y-10">

            {/* 1. General Statement */}
            <section className="bg-white rounded-2xl border border-slate-200 p-8 shadow-sm">
              <h2 className="text-lg font-bold text-[#0B3A63] mb-4">
                1. Digital service refund conditions
              </h2>
              <p className="text-sm text-slate-600 leading-relaxed">
                Certif-Scope provides an instantly delivered digital service. Once payment is confirmed,
                the attestation is generated automatically and immediately available for download.
              </p>
              <p className="text-sm text-slate-600 mt-4 leading-relaxed">
                Under EU Directive 2011/83/UE on consumer rights, the right of withdrawal does
                <strong> not apply</strong> to digital services executed immediately with user consent.
              </p>
            </section>

            {/* 2. Instant Delivery Confirmation */}
            <section className="bg-white rounded-2xl border border-slate-200 p-8 shadow-sm">
              <h2 className="text-lg font-bold text-[#0B3A63] mb-4">
                2. Instant digital delivery confirmation
              </h2>
              <p className="text-sm text-slate-600 leading-relaxed">
                By ordering an attestation, the user explicitly acknowledges that:
              </p>
              <ul className="list-disc list-inside text-sm text-slate-600 mt-2 leading-relaxed">
                <li>The service is executed immediately upon payment.</li>
                <li>The PDF is generated automatically after confirmation.</li>
                <li>No cancellation is possible after generation begins.</li>
              </ul>
            </section>

            {/* 3. Non-refundable Situations */}
            <section className="bg-white rounded-2xl border border-slate-200 p-8 shadow-sm">
              <h2 className="text-lg font-bold text-[#0B3A63] mb-4">
                3. Non-refundable situations
              </h2>
              <p className="text-sm text-slate-600 leading-relaxed">
                Refunds cannot be issued in the following circumstances:
              </p>
              <ul className="list-disc list-inside text-sm text-slate-600 mt-2 leading-relaxed">
                <li>The attestation has been generated successfully.</li>
                <li>The user entered incorrect data.</li>
                <li>The PDF was downloaded but not used.</li>
                <li>A bank, insurer or partner requests a different format.</li>
              </ul>
            </section>

            {/* 4. Refund Exceptions */}
            <section className="bg-white rounded-2xl border border-slate-200 p-8 shadow-sm">
              <h2 className="text-lg font-bold text-[#0B3A63] mb-4">
                4. Exceptional refund cases
              </h2>
              <p className="text-sm text-slate-600 leading-relaxed">
                Refunds may be granted only in exceptional cases:
              </p>
              <ul className="list-disc list-inside text-sm text-slate-600 mt-2 leading-relaxed">
                <li>No PDF was generated due to technical failure.</li>
                <li>The user was charged twice (duplicate payment).</li>
              </ul>
              <p className="text-sm text-slate-600 mt-4 leading-relaxed">
                All refund requests are manually reviewed by support.
              </p>
            </section>

            {/* 5. Contact */}
            <section className="bg-white rounded-2xl border border-slate-200 p-8 shadow-sm">
              <h2 className="text-lg font-bold text-[#0B3A63] mb-4">
                5. Contact for refund requests
              </h2>
              <p className="text-sm text-slate-600 leading-relaxed">
                For refund-related questions (technical failures only), contact:<br />
                <strong>support@certif-scope.com</strong>
              </p>
            </section>
          </div>

          <div className="mt-16 pt-8 border-t border-slate-200 text-center text-xs text-slate-400">
            Last updated: January 2026
          </div>
        </div>
      </div>
    </>
  );
              }
