import Link from 'next/link';

export default function Regulation() {
  return (
    <div className="min-h-screen bg-[#F8FAFC] text-[#1E293B]">
      <div className="max-w-4xl mx-auto px-6 py-24">

        <Link
          href="/"
          className="inline-block mb-10 text-sm font-semibold text-[#1FB6C1] hover:text-[#17A2AC]"
        >
          ← Back to Certif-Scope
        </Link>

        <h1 className="text-3xl md:text-4xl font-black mb-12 text-[#0B3A63]">
          Regulatory context for SME carbon footprint reporting
        </h1>

        <div className="space-y-10 text-[#334155]">

          <section>
            <h2 className="text-xl font-bold text-[#0B3A63] mb-3">
              CSRD: what it covers
            </h2>
            <p className="text-sm leading-relaxed">
              The Corporate Sustainability Reporting Directive (CSRD) applies
              directly to large and listed companies operating in the European
              Union. It requires them to publish standardized sustainability
              information, including greenhouse gas emissions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0B3A63] mb-3">
              Scope 3 and the value chain
            </h2>
            <p className="text-sm leading-relaxed">
              Under the CSRD and the ESRS standards, companies must report
              Scope 3 emissions, which include emissions generated by suppliers,
              subcontractors and other partners.
              <br /><br />
              As a result, SMEs are increasingly requested to provide carbon
              footprint information to their clients, even when they are not
              directly subject to CSRD themselves.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0B3A63] mb-3">
              Why the VSME standard exists
            </h2>
            <p className="text-sm leading-relaxed">
              The European Financial Reporting Advisory Group (EFRAG) introduced
              the VSME standard to offer SMEs a simplified and proportionate
              framework for sustainability reporting.
              <br /><br />
              VSME is designed to help SMEs respond efficiently to carbon data
              requests from banks, corporate clients and procurement processes,
              without the complexity of full CSRD compliance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0B3A63] mb-3">
              Where Certif-Scope fits
            </h2>
            <p className="text-sm leading-relaxed">
              Certif-Scope provides a methodological carbon footprint
              attestation aligned with recognized standards (GHG Protocol,
              ADEME Base Empreinte) and consistent with the VSME approach.
              <br /><br />
              It is designed for pre-compliance, partner reporting and ESG
              questionnaires. It does not constitute a statutory CSRD filing,
              a certified audit or a regulatory declaration.
            </p>
          </section>

        </div>

        <div className="mt-16 pt-8 border-t border-slate-200 text-center text-xs text-slate-400">
          Regulatory information provided for explanatory purposes only.
        </div>

      </div>
    </div>
  );
}
