import Head from "next/head";
import Link from "next/link";

export default function SamplePDF() {
  return (
    <>
      <Head>
        <title>Sample Carbon Attestation — Certif-Scope</title>

        <meta
          name="description"
          content="Preview of the official CO₂ attestation generated by Certif-Scope. Includes Scope 1–2–3 indicators, methodology, regulatory context, attestation ID and SHA-256 hash."
        />

        <link rel="canonical" href="https://certif-scope.com/sample" />
        <meta name="robots" content="index, follow" />

        {/* OpenGraph */}
        <meta property="og:title" content="Sample Carbon Attestation — Certif-Scope" />
        <meta
          property="og:description"
          content="View a sample of the official Certif-Scope carbon footprint attestation generated after payment."
        />
        <meta property="og:image" content="https://certif-scope.com/sample-attestation.png" />
        <meta property="og:type" content="article" />

        {/* Twitter */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Sample Carbon Attestation — Certif-Scope" />
        <meta
          name="twitter:description"
          content="Preview of the official structured CO₂ attestation generated by Certif-Scope."
        />
        <meta name="twitter:image" content="https://certif-scope.com/sample-attestation.png" />

        {/* JSON-LD structured data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "DigitalDocument",
              name: "Sample Carbon Attestation",
              description:
                "Sample preview of the official CO₂ attestation generated by Certif-Scope with unique ID, timestamp and verification hash.",
              publisher: {
                "@type": "Organization",
                name: "Certif-Scope",
              },
              fileFormat: "image/png",
              url: "https://certif-scope.com/sample-attestation.png",
            }),
          }}
        />
      </Head>

      <div className="min-h-screen bg-[#F8FAFC] text-[#1E293B]">
        <div className="max-w-3xl mx-auto px-6 py-16">

          {/* BACK */}
          <Link
            href="/"
            className="inline-block mb-10 text-sm font-semibold text-[#1FB6C1] hover:text-[#17A2AC]"
          >
            ← Back to Certif-Scope
          </Link>

          {/* TITLE */}
          <h1 className="text-3xl md:text-4xl font-black mb-6 text-[#0B3A63]">
            Sample Carbon Footprint Attestation
          </h1>

          <p className="text-slate-600 text-sm leading-relaxed mb-4">
            Certif-Scope is a service operated by <strong>TimeProofs</strong>.
          </p>

          <p className="text-slate-600 text-sm leading-relaxed mb-8">
            Below is a visual preview of the official structured CO₂ attestation generated after payment.  
            The actual PDF includes all required compliance elements for banks, insurers, procurement platforms and supply-chain partners.
          </p>

          {/* KEY ELEMENTS */}
          <ul className="text-sm text-slate-700 space-y-1 mb-10">
            <li>• Company identification</li>
            <li>• Scope 1, Scope 2 and Scope 3 CO₂ indicators</li>
            <li>• Methodology and factors summary</li>
            <li>• Regulatory proportionality context (EU / CSRD / ESRS)</li>
            <li>• Unique attestation ID</li>
            <li>• Timestamp of generation</li>
            <li>• SHA-256 verification hash</li>
            <li>• QR code linking to the verification page</li>
          </ul>

          {/* PREVIEW */}
          <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm mb-8">
            <h2 className="text-center font-bold text-[#0B3A63] mb-4">
              Visual Preview
            </h2>

            <img
              src="/sample-attestation.png"
              alt="Sample CO2 Attestation Preview"
              className="w-full rounded-md border"
            />

            <p className="text-center text-xs text-slate-500 mt-2">
              Watermarked preview of the official attestation (non-contractual).
            </p>
          </div>

          {/* DOWNLOAD BUTTON */}
          <a
            href="/sample-attestation.png"
            download="certif-scope-sample-attestation.png"
            className="block w-full text-center bg-[#1FB6C1] text-white font-bold py-4 rounded-xl hover:bg-[#17A2AC] transition"
          >
            Download sample attestation
          </a>

          {/* FOOTER LINKS */}
          <div className="mt-10 text-center text-xs text-[#64748B] space-y-1">
            <p>Relevant information:</p>
            <p>
              <Link href="/legal" className="text-[#1FB6C1]">Legal Notice</Link> ·{" "}
              <Link href="/privacy" className="text-[#1FB6C1]">Privacy Policy</Link> ·{" "}
              <Link href="/refund-policy" className="text-[#1FB6C1]">Refund Policy</Link>
            </p>
          </div>

        </div>
      </div>
    </>
  );
        }
